convert css to sass
document-template-engine/frontend pull request #18
Opened 2023-10-14 10:23 UTC by iavianm

2023-10-14 19:48 UTC, EarthlingWW-ZeitVenus requested changes
Здоров!
Может сивыберем синтаксис scss, он тут будет многим более знаком, чем sass. Лично мне, конечно, все равно. Понимаю, тебе как Ruby-спецу он ближе :)

2023-10-14 19:52 UTC, iavianm commented
> Здоров! Может сивыберем синтаксис scss, он тут будет многим более знаком, чем sass. Лично мне, конечно, все равно. Понимаю, тебе как Ruby-спецу он ближе :)

Ждем отзывов всех ребят, я с тобой согласен, увидел установленный пакет в package.json поэтому конвертнул в него

2023-10-16 11:48 UTC, Kale0n approved these changes
Давайте возьмем sass. Если все за, я бы уже мержила ветки

2023-10-22 10:22 UTC, seyelich requested changes
Я тоже за scss

2023-10-27 12:56 UTC, closed without merging