feature/header --draft
document-template-engine/frontend pull request #35
Opened 2023-10-17 21:04 UTC by Kale0n

Сейчас в хедере есть только самое основное. Еще не прописала нормально пропсы, потому что на меня ругается линт. Также нет отзывчивости у формы поиска, поскольку с ней оказалось сложно - либо делать все через инпут и визуально сливать его с формой, либо убирать все встроенные эффекты с инпута и стилизовать только форму. Поищу еще решение, но если у кого-то есть идеи как правильно - welcome.
Решила все же запушить сегодня, чтобы у нас все же был хоть какой-нибудь хедр. Как я понимаю, его лучше встраивать сразу в какой-нибудь блок.

2023-10-22 10:34 UTC, seyelich requested changes

2023-10-22 10:34 UTC, seyelich commented on src/components/Navbar/Navbar.js
> -					>
Удалила случайно часть тэга, падают ошибки

2023-10-22 11:33 UTC, Kale0n commented
Navbar починен

2023-10-23 09:48 UTC, Kale0n commented
Хедр готов. Теперь нужно прикрутить к нему нужные кнопки

2023-10-23 09:49 UTC, merged