feat: add rental agreement form
document-template-engine/frontend pull request #48
Opened 2023-10-21 17:56 UTC by Kukucapl

2023-10-21 22:05 UTC, Kale0n approved these changes

2023-10-22 11:00 UTC, seyelich commented on src/components/Forms/RentalAgreementForm.jsx
> +const RentalAgreement = ({ form }) => (
экспортируй компонент, чтобы его можно было использовать в других модулях

2023-10-22 11:02 UTC, seyelich requested changes

2023-10-22 11:02 UTC, seyelich commented on src/components/Forms/RentalAgreementForm.jsx
> +// eslint-disable-next-line react/prop-types
Здесь нужно удалить комментарий, отменяющий правило линтера. Нужно прописать тип пропса form. Если не знаешь как это делать, почитай доки и посмотри, как делали в других компонентах (navbar, modal и проч)

2023-10-22 11:09 UTC, seyelich commented
Еще обновился макет. Например, добавилась кнопка Добавить проживающего. Нужно будет добавить этот функционал

2023-10-22 13:59 UTC, Kukucapl commented
Кнопка опосля мвп будет, пока рано говорят

2023-10-22 14:10 UTC, Kukucapl commented on src/components/Forms/RentalAgreementForm.jsx
> +// eslint-disable-next-line react/prop-types
Поделано

2023-10-23 10:19 UTC, iavianm approved these changes

2023-10-23 18:06 UTC, merged